# Basis Sharing Configuration for Mistral 7B on PTB (30% compression)
model_args:
  model_type: "mistral"
  model_name: "mistralai/Mistral-7B-v0.1"
  group_size: 2
  compression_ratio: 30
  context_length: 2048
  stride: 2048

calibration_args:
  dataset_name: "ptb"
  calibration_size: 256
  calib_batch_size: 16
  dataset_cache_dir: null

model_saving:
  save_compressed_model: true
  compressed_model_path: "./compressed_models/mistral_7b_30/ptb"
